### PR TITLE
Update solidity version

### PR DESCRIPTION
**Pull request by qiwu7**

### CODE REVIEW

**Comment by lbeder** [comment]
Hi @qiwu7,

We can't relax the required Solidity version in any contract, apart from contracts/interfaces which are meant to be used externally (i.e., any interface and the `SchemaResolver`). What are you trying to achieve?

**Comment by qiwu7** [comment]
@lbeder Hi thanks for the quick response. I am trying to use eas-contracts together with uniswap v4 contracts, which requires [0.8.20 and above](https://github.com/Uniswap/v4-core/blob/main/src/PoolManager.sol#L2). So this is causing incompatible versions for me when compiling the code.

**Comment by lbeder** [comment]
Right, but both hardhat and foundry support multiple Solidity versions in the same projects, so unless you're trying to mix imports, everything should work. What are you trying to achieve?

**Comment by qiwu7** [comment]
The thing is EAS only allows for 0.8.19 solc version. If I use 0.8.20, the complier will complain about the EAS version being strictly set to `0.8.19`

```
% forge build
[⠰] Compiling...
[⠃] Compiling 106 files with 0.8.20
[⠊] Solc 0.8.20 finished in 429.08ms
Error: 
Compiler run failed:
Error (5333): Source file requires different compiler version (current compiler is 0.8.20+commit.a1b79de6.Darwin.appleclang) - note that nightly builds are considered to be strictly less than the released version
 --> lib/eas-contracts/contracts/EAS.sol:3:1:
  |
3 | pragma solidity 0.8.19;
  | ^^^^^^^^^^^^^^^^^^^^^^^

Error (5333): Source file requires different compiler version (current compiler is 0.8.20+commit.a1b79de6.Darwin.appleclang) - note that nightly builds are considered to be strictly less than the released version
 --> lib/eas-contracts/contracts/SchemaRegistry.sol:3:1:
  |
3 | pragma solidity 0.8.19;
  | ^^^^^^^^^^^^^^^^^^^^^^^

Error (5333): Source file requires different compiler version (current compiler is 0.8.20+commit.a1b79de6.Darwin.appleclang) - note that nightly builds are considered to be strictly less than the released version
 --> lib/eas-contracts/contracts/eip1271/EIP1271Verifier.sol:3:1:
  |
3 | pragma solidity 0.8.19;
  | ^^^^^^^^^^^^^^^^^^^^^^^
```


If I use 0.8.19 solc, it will also error out since Univ4 contracts needs the complier version to be at least 0.8.20

```
forge build
[⠒] Compiling...
[⠊] Compiling 106 files with 0.8.19
[⠒] Solc 0.8.19 finished in 374.02ms
Error: 
Compiler run failed:
Error (5333): Source file requires different compiler version (current compiler is 0.8.19+commit.7dd6d404.Darwin.appleclang) - note that nightly builds are considered to be strictly less than the released version

Error (5333): Source file requires different compiler version (current compiler is 0.8.19+commit.7dd6d404.Darwin.appleclang) - note that nightly builds are considered to be strictly less than the released version
 --> lib/v4-core/src/../test/utils/Deployers.sol:2:1:
  |
2 | pragma solidity ^0.8.20;
  | ^^^^^^^^^^^^^^^^^^^^^^^^

Error (5333): Source file requires different compiler version (current compiler is 0.8.19+commit.7dd6d404.Darwin.appleclang) - note that nightly builds are considered to be strictly less than the released version
 --> lib/v4-core/src/Claims.sol:2:1:
  |
2 | pragma solidity ^0.8.20;
  | ^^^^^^^^^^^^^^^^^^^^^^^^

Error (5333): Source file requires different compiler version (current compiler is 0.8.19+commit.7dd6d404.Darwin.appleclang) - note that nightly builds are considered to be strictly less than the released version
 --> lib/v4-core/src/NoDelegateCall.sol:2:1:
  |
2 | pragma solidity ^0.8.20;
  | ^^^^^^^^^^^^^^^^^^^^^^^^

Error (5333): Source file requires different compiler version (current compiler is 0.8.19+commit.7dd6d404.Darwin.appleclang) - note that nightly builds are considered to be strictly less than the released version
 --> lib/v4-core/src/Owned.sol:2:1:
  |
2 | pragma solidity ^0.8.20;
  | ^^^^^^^^^^^^^^^^^^^^^^^^

Error (5333): Source file requires different compiler version (current compiler is 0.8.19+commit.7dd6d404.Darwin.appleclang) - note that nightly builds are considered to be strictly less than the released version
 --> lib/v4-core/src/PoolManager.sol:2:1:
  |
2 | pragma solidity ^0.8.20;
  | ^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by lbeder** [comment]
Foundry supports multiple solidity versions in the same project. Have you added `auto_detect_solc = true` to your profile?

**Comment by qiwu7** [comment]
Yup i have tried that, and it doesn't seem to work. Also, Uni v4 currently uses a custom solc binary to compile. So I am not sure how to specify different versions properly. I don't know if they will move away from this custom solc binary in the future. 

See more context here: https://github.com/Uniswap/v4-core/pull/395

**Comment by lbeder** [comment]
Very strange indeed. Is there any chance you could share your code or create a sample project which reproduces your settings? I can try helping you find a workaround.

**Pull request closed without merging**
