### PR TITLE
Update base deployment

### PR DESCRIPTION
**Pull request by Chomtana**
Base uses the latest OP stack fork patch so 0x4200000000000000000000000000000000000021 and 0x4200000000000000000000000000000000000020 are available and should be used instead.

### CODE REVIEW

**Comment by lbeder** [comment]
Hey @Chomtana, are you sure it's up to date? We understood from the Optimism team that Base kind of "missed the train" and having EAS predeploy will require additional coordination.

**Comment by Chomtana** [comment]
image

Base Etherscan shows genesis deployment don't sure if it works. Will try on a superhack product.

**Comment by slavik0329** [comment]
Looks like it's testnet only

**Comment by Chomtana** [comment]
image

Mainnet also show the same? It's great if you can try bootstraping your initial schema and attestation to see if its work.

**Comment by Chomtana** [comment]
image

OK. Has proxy but not initialized = no contract behind proxy

**Pull request closed without merging**
